name       : slick-greeter
version    : 1.5.6
release    : 19
source     :
    - https://github.com/linuxmint/slick-greeter/archive/refs/tags/1.5.6.tar.gz : a4d0de78733df0dd485081d17b1cd42a2adcb8449ddf9983d526a1b66626fa19
homepage   : https://github.com/linuxmint/slick-greeter
license    : GPL-3.0-or-later
component  : desktop.lightdm
summary    : A stylish LightDM greeter
description: |
    A fork of the Unity Greeter, provides a stylish login greeter for LightDM
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(xext)
    - gnome-common
    - vala
conflicts  : gdm
setup      : |
    %apply_patches
    %autogen
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/60-slick-greeter.conf $installdir/usr/share/lightdm/lightdm.conf.d/60-slick-greeter.conf
    # Required for our patched slick-greeter
    install -Dm00644 $pkgfiles/slick-greeter-pointer.png $installdir/usr/share/pixmaps/slick-greeter-pointer.png
