name       : slick-greeter
version    : 1.2.9
release    : 11
source     :
    - https://github.com/linuxmint/slick-greeter/archive/1.2.9.tar.gz : 2b84fbc9105ebca9002b3eaf85774086fbce377908e4c9fd948705b97faac93b
license    : GPL-3.0-or-later
component  : desktop.lightdm
summary    : A stylish LightDM greeter
description: |
    A fork of the Unity Greeter, provides a stylish login greeter for LightDM
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xext)
    - gnome-common
    - intltool
    - vala
conflicts  : gdm
setup      : |
    %apply_patches
    %autogen
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/60-slick-greeter.conf $installdir/usr/share/lightdm/lightdm.conf.d/60-slick-greeter.conf
    # Required for our patched slick-greeter
    install -Dm00644 $pkgfiles/slick-greeter-pointer.png $installdir/usr/share/pixmaps/slick-greeter-pointer.png
