name       : slick-greeter
version    : 1.8.2
release    : 27
source     :
    - https://github.com/linuxmint/slick-greeter/archive/refs/tags/1.8.2.tar.gz : a0b788e8960ca440a17df49b510a4fafabcac064f15b682c4c858cf5a4e8d876
homepage   : https://github.com/linuxmint/slick-greeter
license    : GPL-3.0-or-later
component  : desktop.lightdm
summary    : A stylish LightDM greeter
description: |
    A fork of the Unity Greeter, provides a stylish login greeter for LightDM
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(xapp)
    - pkgconfig(xext)
    - pkgconfig(xkbfile)
    - gettext-devel
    - gnome-common
    - vala
rundeps    :
    - breeze-cursor-theme
conflicts  : gdm
setup      : |
    %apply_patches
    %autogen
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/60-slick-greeter.conf $installdir/usr/share/lightdm/lightdm.conf.d/60-slick-greeter.conf
