name       : slick-greeter
version    : 1.2.2
release    : 6
source     :
    - https://github.com/linuxmint/slick-greeter/archive/1.2.2.tar.gz : ea5e53e1beddda097fc6e0733bc5dc5c143341504b34f7165357e87ed7b7b52b
license    : GPL-3.0-or-later
component  : desktop.lightdm
summary    : A stylish LightDM greeter
description: |
    A fork of the Unity Greeter, provides a stylish login greeter for LightDM
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xext)
    - gnome-common
    - intltool
    - vala
conflicts  : gdm
setup      : |
    %patch -p1 < $pkgfiles/0001-data-Apply-sane-Solus-default-styling.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/60-slick-greeter.conf $installdir/usr/share/lightdm/lightdm.conf.d/60-slick-greeter.conf
