name       : slick-greeter
version    : 1.0.8
release    : 1
source     :
    - https://github.com/linuxmint/slick-greeter/archive/1.0.8.tar.gz : 20df7dbb03f65a1e8a74beb0db0b411b2893eb5a7fdbc7514014af01e59dec7d
license    : GPL-3.0
component  : desktop.lightdm
summary    : A stylish LightDM greeter
description: |
    A fork of the Unity Greeter, provides a stylish login greeter for LightDM
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xext)
    - gnome-common
    - intltool
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-data-Apply-sane-Solus-default-styling.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/60-slick-greeter.conf $installdir/usr/share/lightdm/lightdm.conf.d/60-slick-greeter.conf
