name       : slick-greeter
version    : 1.6.0
release    : 23
source     :
    - https://github.com/linuxmint/slick-greeter/archive/refs/tags/1.6.0.tar.gz : 48375ee4a3d7625f4caa9708448c97efe818f1b074764951281992eccaee4b3b
homepage   : https://github.com/linuxmint/slick-greeter
license    : GPL-3.0-or-later
component  : desktop.lightdm
summary    : A stylish LightDM greeter
description: |
    A fork of the Unity Greeter, provides a stylish login greeter for LightDM
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(xext)
    - gnome-common
    - vala
rundeps    :
    - breeze-cursor-theme
conflicts  : gdm
setup      : |
    %apply_patches
    %autogen
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/60-slick-greeter.conf $installdir/usr/share/lightdm/lightdm.conf.d/60-slick-greeter.conf
